-- AlterTable
ALTER TABLE "Assessment" ADD COLUMN     "anchorGroundConnection" DOUBLE PRECISION,
ADD COLUMN     "anchorLowerBodyMechanics" DOUBLE PRECISION,
ADD COLUMN     "anchorScore" DOUBLE PRECISION,
ADD COLUMN     "anchorStance" DOUBLE PRECISION,
ADD COLUMN     "anchorWeightShift" DOUBLE PRECISION,
ADD COLUMN     "assessmentName" TEXT,
ADD COLUMN     "avgTimingAccuracy" DOUBLE PRECISION,
ADD COLUMN     "barrelRate" DOUBLE PRECISION,
ADD COLUMN     "biomechanicalComposite" DOUBLE PRECISION,
ADD COLUMN     "biomechanicalGrade" TEXT,
ADD COLUMN     "breakingBallContact" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "breakingBallContactRate" DOUBLE PRECISION,
ADD COLUMN     "breakingBallPitches" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "callAccuracy" DOUBLE PRECISION,
ADD COLUMN     "chaseRate" DOUBLE PRECISION,
ADD COLUMN     "coachNotes" TEXT,
ADD COLUMN     "cognitiveGrade" TEXT,
ADD COLUMN     "contactCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "contactQualityGrade" TEXT,
ADD COLUMN     "contactRate" DOUBLE PRECISION,
ADD COLUMN     "earlySwingRate" DOUBLE PRECISION,
ADD COLUMN     "earlySwings" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "engineCorePower" DOUBLE PRECISION,
ADD COLUMN     "engineHipRotation" DOUBLE PRECISION,
ADD COLUMN     "engineScore" DOUBLE PRECISION,
ADD COLUMN     "engineSeparation" DOUBLE PRECISION,
ADD COLUMN     "engineTorsoMechanics" DOUBLE PRECISION,
ADD COLUMN     "exitVelocityAvg" DOUBLE PRECISION,
ADD COLUMN     "exitVelocityMax" DOUBLE PRECISION,
ADD COLUMN     "fastballContact" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "fastballContactRate" DOUBLE PRECISION,
ADD COLUMN     "fastballPitches" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "fooledByVelocity" DOUBLE PRECISION,
ADD COLUMN     "foulCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "hardContactCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "hardContactRate" DOUBLE PRECISION,
ADD COLUMN     "hardHitRate" DOUBLE PRECISION,
ADD COLUMN     "impulseControlScore" DOUBLE PRECISION,
ADD COLUMN     "lateSwingRate" DOUBLE PRECISION,
ADD COLUMN     "lateSwings" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "launchAngleAvg" DOUBLE PRECISION,
ADD COLUMN     "launchAngleMax" DOUBLE PRECISION,
ADD COLUMN     "lineDriverate" DOUBLE PRECISION,
ADD COLUMN     "missCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "neuroCompositeScore" DOUBLE PRECISION,
ADD COLUMN     "offspeedContact" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "offspeedContactRate" DOUBLE PRECISION,
ADD COLUMN     "offspeedPitches" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "onTimeSwingRate" DOUBLE PRECISION,
ADD COLUMN     "onTimeSwings" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "overallGrade" TEXT,
ADD COLUMN     "pitchTestCompleted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "pitchTypeRecognition" DOUBLE PRECISION,
ADD COLUMN     "recommendations" JSONB,
ADD COLUMN     "strengths" JSONB,
ADD COLUMN     "strikeZoneJudgment" DOUBLE PRECISION,
ADD COLUMN     "sweetSpotRate" DOUBLE PRECISION,
ADD COLUMN     "swingDecisionQuality" DOUBLE PRECISION,
ADD COLUMN     "swingRate" DOUBLE PRECISION,
ADD COLUMN     "swingsInZone" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "swingsOutOfZone" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "takeRate" DOUBLE PRECISION,
ADD COLUMN     "takesInZone" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "takesOutOfZone" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "testDate" TIMESTAMP(3),
ADD COLUMN     "testNotes" TEXT,
ADD COLUMN     "timingControlScore" DOUBLE PRECISION,
ADD COLUMN     "totalPitches" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "trajectoryScore" DOUBLE PRECISION,
ADD COLUMN     "velocityAdaptation" DOUBLE PRECISION,
ADD COLUMN     "videoId" TEXT,
ADD COLUMN     "weaknesses" JSONB,
ADD COLUMN     "whipArmPath" DOUBLE PRECISION,
ADD COLUMN     "whipBatPath" DOUBLE PRECISION,
ADD COLUMN     "whipBatSpeed" DOUBLE PRECISION,
ADD COLUMN     "whipConnection" DOUBLE PRECISION,
ADD COLUMN     "whipScore" DOUBLE PRECISION,
ADD COLUMN     "zoneControl" DOUBLE PRECISION,
ADD COLUMN     "zoneRecognitionAccuracy" DOUBLE PRECISION,
ALTER COLUMN "purchaseDate" DROP NOT NULL,
ALTER COLUMN "purchaseDate" DROP DEFAULT,
ALTER COLUMN "amountPaid" DROP NOT NULL;

-- CreateIndex
CREATE INDEX "Assessment_videoId_idx" ON "Assessment"("videoId");

-- AddForeignKey
ALTER TABLE "Assessment" ADD CONSTRAINT "Assessment_videoId_fkey" FOREIGN KEY ("videoId") REFERENCES "Video"("id") ON DELETE SET NULL ON UPDATE CASCADE;
